# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SBQYrucSOVvWtFEf_Z7XW61N7Um76tHO
"""

import requests


from datetime import datetime
api_key = 'import requests'

from datetime import datetime
api_key = '73a04bc379724d2263e80858f213335c'
location = input("Enter the city name: ")

complete_api_link= "https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link= requests.get(complete_api_link)
api_data = api_link.json()


temp_city= ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt= api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime ("%d %b %Y | %I:%M:%S %p")

print ("-------------------------------------------------------------------")
print ("Weather stats of - {} || {}".format(location.upper(), date_time))
print ("--------------------------------------------------------------------")
print ("Current temperature : {:.2f} deg C".format(temp_city))
print ("Current weather description :",weather_desc)
print ("Current humidity level :",hmdt, '%')
print ("Current wind speed :",wind_spd, 'kmph')

slocation=str(location)
stemp_city=str(temp_city)
sweather_desc=str(weather_desc)
shmdt=str(hmdt)
swind_spd=str(wind_spd)

f = open('weather.txt','a')
f.write("\nLocation : ")
f.write(slocation) 
f.write("\nCurrent temperature : ")
f.write(stemp_city) 
f.write(" deg C") 
f.write("\nCurrent weather description : ") 
f.write(sweather_desc) 
f.write("\nCurrent humidity level  : ")
f.write(shmdt) 
f.write(" %") 
f.write("\nCurrent wind speed : ")
f.write(swind_spd)
f.write(" kmph") 
f.close()